FROM centos:7
# Date:2023.11.15
RUN yum install -y strace enscript curl wget swig bzip2 ghostscript autoconf automake cmake Cython \
    glibc-devel zlib-devel python-devel libcurl libpng libcurl-devel bzip2-devel  \
    libtool-ltdl libtool-ltdl-devel libxml2-devel pigz ncurses-devel libffi-devel libxslt-devel sqlite-devel tbb-devel audit audit-libs audit-libs-devel \
    gcc-gfortran libicu-devel make openblas-devel pango pcre2-devel tcl tk unzip which zip \
    perl-CPAN perl-IPC-Cmd perl-WWW-Curl java-11-openjdk java-11-openjdk-devel gcc gcc-c++ glibc-headers libstdc++-static git patch file

RUN yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && yum install -y python2-pip openssl-devel htslib

#make directory
RUN mkdir -p /raw_data/ /database/ /project/ /outdir/ /software/
RUN cd /software/ && wget https://www.openssl.org/source/openssl-1.1.1m.tar.gz --no-check-certificate &&  \
    tar xzvf openssl-1.1.1m.tar.gz && cd  openssl-1.1.1m && ./config --prefix=/software/openssl/ && make -j20 && make install &&  \
    ln -s /software/openssl/bin/openssl /usr/bin/openssl &&  \
    ln -s /software/openssl/include/openssl /usr/include/openssl &&  \
    echo "/software/openssl/lib" >> /etc/ld.so.conf && ldconfig -v

#Install python3
RUN cd /software/ && wget https://www.python.org/ftp/python/3.11.0/Python-3.11.0.tgz &&  \
    tar xvf Python-3.11.0.tgz && cd Python-3.11.0  \
    && ./configure --with-openssl=/software/openssl/ --prefix=/software/Python-v3.11.0 && make -j20 && make install

#use_2to3 is invalid.
RUN /software/Python-v3.11.0/bin/pip3 install setuptools==57.5.0
RUN /software/Python-v3.11.0/bin/pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple tensorflow scikit-learn PyVCF RSeQC cutadapt tornado seaborn  \
    edlib CNVkit PyYAML wheel parse2csv openpyxl pandas numpy configparser biopython pysam matplotlib  \
    Cython parse CrossMap cryptography easycython HTSeq seaborn pandas

#Install R(https://cran.r-project.org/index.html)
RUN cd /software/ && wget https://cloud.r-project.org/src/base/R-4/R-4.2.3.tar.gz &&  \
    tar xzvf R-4.2.3.tar.gz && cd R-4.2.3 && ./configure --enable-R-shlib --with-readline=no --with-x=no --enable-memory-profiling && make -j20 && make install &&  \
    echo "r <- getOption('repos'); r['CRAN'] <- 'https://cloud.r-project.org/'; options(repos = r);" > ~/.Rprofile

RUN Rscript -e "install.packages(c(\"BiocManager\",\"tidyverse\",\"sequenza\"))" && \
    Rscript -e "BiocManager::install(c(\"Rgraphviz\",\"SPIA\",\"hwriter\", \
    \"hwriter\",\"pathview\",\"WGCNA\",\"DESeq2\",\"vegan\",\"edgeR\",\"clusterProfiler\", \
    \"RCurl\",\"GSVA\",\"gage\",\"GenomicRanges\",\"GenomicAlignments\", \
    \"biocGraph\",\"safe\",\"topGO\",\"ComplexHeatmap\",\"KEGGgraph\",\"EDASeq\",\"ReportingTools\",\"DNAcopy\",\"NOISeq\"))"

###java####
RUN cd /software/ && wget https://builds.openlogic.com/downloadJDK/openlogic-openjdk-jre/17.0.9+9/openlogic-openjdk-jre-17.0.9+9-linux-x64.tar.gz && tar xzvf openlogic-openjdk-jre-17.0.9+9-linux-x64.tar.gz && \
    wget https://builds.openlogic.com/downloadJDK/openlogic-openjdk-jre/8u392-b08/openlogic-openjdk-jre-8u392-b08-linux-x64.tar.gz && tar xzvf openlogic-openjdk-jre-8u392-b08-linux-x64.tar.gz

###bwa+seqtk#######
RUN cd /software && git clone https://github.com/lh3/bwa.git && cd bwa && make &&  \
    cd /software && git clone https://github.com/lh3/seqtk.git && cd seqtk && make

###fastp+picard+varscan+MSIsensor-pro+abra2+fgbio+delly+sambamba+genefuse######
RUN cd /usr/bin/ && wget http://opengene.org/fastp/fastp && chmod a+x ./fastp &&  \
    wget https://github.com/broadinstitute/picard/releases/download/3.1.1/picard.jar && chmod a+x picard.jar &&  \
    wget https://github.com/dkoboldt/varscan/releases/download/v2.4.6/VarScan.v2.4.6.jar && chmod a+x VarScan.v2.4.6.jar &&  \
    wget https://github.com/xjtu-omics/msisensor-pro/raw/master/binary/msisensor-pro && chmod a+x msisensor-pro && \
    wget https://github.com/mozack/abra2/releases/download/v2.24/abra2-2.24.jar && chmod a+x abra2-2.24.jar && \
    wget https://github.com/fulcrumgenomics/fgbio/releases/download/2.1.0/fgbio-2.1.0.jar && chmod a+x fgbio-2.1.0.jar &&  \
    wget https://github.com/dellytools/delly/releases/download/v1.1.8/delly_v1.1.8_linux_x86_64bit && chmod a+x delly_v1.1.8_linux_x86_64bit &&  \
    wget http://opengene.org/GeneFuse/genefuse && chmod a+x ./genefuse &&  \
    wget https://github.com/biod/sambamba/releases/download/v1.0.1/sambamba-1.0.1-linux-amd64-static.gz &&  \
    gunzip sambamba-1.0.1-linux-amd64-static.gz && chmod a+x ./sambamba-1.0.1-linux-amd64-static

###samtools+bcftools+htslib+bedops####
RUN cd /software/ && wget https://github.com/samtools/samtools/releases/download/1.18/samtools-1.18.tar.bz2 &&  \
    tar xjvf samtools-1.18.tar.bz2 && cd samtools-1.18 && ./configure --prefix=/software/samtools-v1.18 && make -j20 && make install &&  \
    cd /software/ && wget https://github.com/samtools/bcftools/releases/download/1.18/bcftools-1.18.tar.bz2 &&  \
    tar xjvf bcftools-1.18.tar.bz2 && cd bcftools-1.18 && ./configure --prefix=/software/bcftools-v1.18 && make -j20 && make install &&  \
    cd /software/ && wget https://github.com/samtools/htslib/releases/download/1.18/htslib-1.18.tar.bz2 &&  \
    tar xjvf htslib-1.18.tar.bz2 && cd htslib-1.18 && ./configure --prefix=/software/htslib-v1.18 && make -j20 && make install &&  \
    mkdir -p /software/bedops && cd /software/bedops && wget https://github.com/bedops/bedops/releases/download/v2.4.41/bedops_linux_x86_64-v2.4.41.tar.bz2 &&  \
    tar xjvf bedops_linux_x86_64-v2.4.41.tar.bz2 && rm -rf bedops_linux_x86_64-v2.4.41.tar.bz2

###VarDict+bedtools####
RUN cd /software/ && wget https://github.com/AstraZeneca-NGS/VarDictJava/releases/download/v1.8.3/VarDict-1.8.3.tar && tar xvf VarDict-1.8.3.tar  \
    && wget https://github.com/arq5x/bedtools2/releases/download/v2.31.1/bedtools-2.31.1.tar.gz && tar xzvf bedtools-2.31.1.tar.gz && cd bedtools2 && make -j20 && make install

###Manta+strelka#####
RUN cd /software/ && wget https://github.com/Illumina/manta/releases/download/v1.6.0/manta-1.6.0.release_src.tar.bz2 && tar -xjvf manta-1.6.0.release_src.tar.bz2 &&  \
    mkdir build && cd build && ../manta-1.6.0.release_src/configure --jobs=20 --prefix=/software/manta-v1.6.0 && make -j20 install &&  \
    wget https://github.com/Illumina/strelka/releases/download/v2.9.10/strelka-2.9.10.release_src.tar.bz2 && tar -xjvf strelka-2.9.10.release_src.tar.bz2 &&  \
    mkdir build && cd build && ../strelka-2.9.10.release_src/configure --jobs=20 --prefix=/software/strelka-v2.9.10 && make -j20 install

####GATK+rtg-tools+SomaticSniper#####
RUN cd /software/ && wget https://github.com/RealTimeGenomics/rtg-tools/releases/download/3.12.1/rtg-tools-3.12.1-linux-x64.zip && unzip rtg-tools-3.12.1-linux-x64.zip \
    && wget https://github.com/broadinstitute/gatk/releases/download/4.4.0.0/gatk-4.4.0.0.zip && unzip gatk-4.4.0.0.zip && \
    wget https://github.com/genome/somatic-sniper/archive/refs/tags/v1.0.5.0.zip && unzip v1.0.5.0.zip && mkdir somatic-sniper-1.0.5.0/build && cd somatic-sniper-1.0.5.0/build && cmake ../ &&  \
    make deps && make -j && make test

##gcc 7.1.0####
RUN cd /software/ && wget https://mirrors.ustc.edu.cn/gnu/gcc/gcc-7.1.0/gcc-7.1.0.tar.bz2 && tar xjvf gcc-7.1.0.tar.bz2 && cd gcc-7.1.0 &&  \
    ./contrib/download_prerequisites && rm -rf /software/build/* && cd /software/build &&  \
    ../gcc-7.1.0/configure --prefix=/software/gcc-v7.1.0 --enable-languages=c,c++,fortran,go --disable-multilib && make -j20 && make install

###Minimap2+pindel####
RUN cd /software/ && wget https://github.com/lh3/minimap2/releases/download/v2.26/minimap2-2.26_x64-linux.tar.bz2 && tar xjvf minimap2-2.26_x64-linux.tar.bz2 \
    && wget https://github.com/genome/pindel/archive/refs/tags/v0.2.5b8.tar.gz && tar xzvf v0.2.5b8.tar.gz && cd pindel-0.2.5b8 && ./INSTALL /software/htslib-1.18/

###delete software
RUN cd /software/ && rm -rf *.gz *.tgz *.bz2 *.zip Python-3.11.0 R-4.2.3 samtools-1.18 bcftools-1.18 htslib-1.18 gcc-7.1.0 openssl-1.1.1m build manta-1.6.0.release_src